[project]
name = "comfyui_snacknodes"  # Unique identifier for your node. Immutable after creation.
description = "A collection of custom nodes for ComfyUI with image processing capabilities"
version = "0.0.1"  # Custom Node version. Must be semantically versioned.
license = { file = "LICENSE" }
dependencies = [
    "torch==2.0.0",
    "numpy==1.21.0",
    "pillow==9.0.0",
    "comfyui==1.0.0"
]

[project.urls]
Repository = "https://github.com/linksluckytime/comfyui_snacknodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "linksluckytime"  # Publisher ID from Comfy Registry Website
DisplayName = "SnackNodes Image 🍿"  # Display name for the Custom Node
Icon = "🍿"  # Emoji icon
