# pyproject.toml
[build-system]
requires = ["setuptools>=65.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "comfyui_snacknodes"
description = "A comprehensive collection of ComfyUI nodes designed to reduce reliance on multiple third-party node packages."
version = "0.0.5"
authors = [
    {name = "linksluckytime", email = "linksluckytime@gmail.com"}
]
readme = "README.md"
license = {text = "GNU General Public License v3"}
dependencies = [
    "torch",
    "numpy",
    "pillow",
    "opencv-python-headless"
]

[project.urls]
Repository = "https://github.com/linksluckytime/comfyui_snacknodes"

[project.optional-dependencies]
face = [
    "dlib",
]
dev = [
    "bump-my-version",
    "coverage",
    "mypy",
    "pre-commit",
    "pytest",
    "ruff",
]

[tool.setuptools]
packages = ["comfyui_snacknodes", "nodes", "utils", "config"]
package-dir = {"comfyui_snacknodes" = "."}

[tool.setuptools.package-data]
"*" = ["*.png", "*.json"]
"comfyui_snacknodes" = ["web/*"]

[tool.comfy]
PublisherId = "linksluckytime"
DisplayName = "SnackNodes 🍿"
Icon = "https://raw.githubusercontent.com/linksluckytime/comfyui_snacknodes/main/web/icon.png"